const weatherCodeDescriptions = {
  0: "clear skies",
  1: "it to be mostly clear",
  2: "it to be partly cloudy",
  3: "it to be overcast",
  45: "it to be foggy",
  48: "to see rime fog",
  51: "a little light drizzle",
  53: "some moderate drizzle",
  55: "your getting a dense drizzle",
  56: "some light freezing drizzle",
  57: "your getting a dense freezing drizzle",
  61: "a nice light rain",
  63: "a nice moderate rain",
  65: "a beautify heavy rain",
  66: "light freezing rain. crazy",
  67: "heavy freezing rain. absoluley crazy",
  71: "light snowfall",
  73: "moderate snowfall",
  75: "heavy snowfall",
  77: "snow grains",
  80: "some light rain showers",
  81: "some moderate rain showers",
  82: "some heavy rain showers",
  85: "some light snow showers",
  86: "some heavy snow showers",
  95: "an amazing thunderstorms",
  96: "a thunderstorm with slight hail. what!!!!",
  99: "a thunderstorms with heavy hail. damn",
};

export const weatherCodeHeadlines = {
  0: "Clear Skies",
  1: "Mostly Clear",
  2: "Partly Cloudy",
  3: "Overcast",
  45: "Foggy",
  48: "Rime Fog",
  51: "Light Drizzle",
  53: "Moderate Drizzle",
  55: "Dense Drizzle",
  56: "Light Freezing Drizzle",
  57: "Dense Freezing Drizzle",
  61: "Light Rain",
  63: "Moderate Rain",
  65: "Heavy Rain",
  66: "Light Freezing Rain",
  67: "Heavy Freezing Rain",
  71: "Light Snow",
  73: "Moderate Snow",
  75: "Heavy Snow",
  77: "Snow Grains",
  80: "Light Rain Showers",
  81: "Moderate Rain Showers",
  82: "Heavy Rain Showers",
  85: "Light Snow Showers",
  86: "Heavy Snow Showers",
  95: "Thunderstorms",
  96: "Thunderstorms w/ Hail",
  99: "Severe Thunderstorms",
};

export default weatherCodeDescriptions;
