const weatherCodeDescriptions = {
  0: "clear skies",
  1: "it to be mostly clear",
  2: "it to be partly cloudy",
  3: "it to be overcast",
  45: "it to be foggy",
  48: "to see rime fog",
  51: "a little light drizzle",
  53: "some moderate drizzle",
  55: "your getting a dense drizzle",
  56: "some light freezing drizzle",
  57: "your getting a dense freezing drizzle",
  61: "a nice light rain",
  63: "a nice moderate rain",
  65: "a beautify heavy rain",
  66: "light freezing rain. crazy",
  67: "heavy freezing rain. absoluley crazy",
  71: "light snowfall",
  73: "moderate snowfall",
  75: "heavy snowfall",
  77: "snow grains",
  80: "some light rain showers",
  81: "some moderate rain showers",
  82: "some heavy rain showers",
  85: "some light snow showers",
  86: "some heavy snow showers",
  95: "an amazing thunderstorms",
  96: "a thunderstorm with slight hail. what!!!!",
  99: "a thunderstorms with heavy hail. damn",
};

export default weatherCodeDescriptions;
