//////////////////////////////////////
export const feeds = [
  { feedTitle: "MacRumors", feedUrl: "https://feeds.macrumors.com/MacRumors-Front" },
  { feedTitle: "The Verge", feedUrl: "https://www.theverge.com/rss/index.xml" },
  { feedTitle: "Wired", feedUrl: "https://www.wired.com/feed/rss" },
  { feedTitle: "Engadget", feedUrl: "https://www.engadget.com/rss.xml" },
  { feedTitle: "Acme Packing Company", feedUrl: "https://www.acmepackingcompany.com/rss/current.xml" },
  { feedTitle: "Packernet", feedUrl: "https://www.packernet.com/rss/articles.php" },
  { feedTitle: "Bleacher Nation Cubs", feedUrl: "https://www.bleachernation.com/cubs/feed/" },
  { feedTitle: "Bleed Cubbie Blue", feedUrl: "https://www.bleedcubbieblue.com/rss/current.xml" },
  { feedTitle: "Den of Geek", feedUrl: "https://www.denofgeek.com/feed/" },
  { feedTitle: "Hacker News", feedUrl: "https://news.ycombinator.com/rss" },
  { feedTitle: "Hacker Noon", feedUrl: "https://cdn.hackernoon.com/feed" },
  { feedTitle: "CoinDesk", feedUrl: "https://www.coindesk.com/arc/outboundfeeds/rss/" },
  { feedTitle: "Formula 1", feedUrl: "https://www.formula1.com/en/latest/all.xml" },
  { feedTitle: "Awful Announcing", feedUrl: "https://awfulannouncing.com/feed" },
  { feedTitle: "Yahoo Sports", feedUrl: "https://sports.yahoo.com/rss/" },
  { feedTitle: "Pitcher List", feedUrl: "https://www.pitcherlist.com/feed/" },
  { feedTitle: "CBS Sports MLB", feedUrl: "https://www.cbssports.com/rss/headlines/mlb/" },
  { feedTitle: "The Athletic MLB", feedUrl: "https://theathletic.com/mlb/?rss=1" },
  { feedTitle: "MLB Trade Rumors", feedUrl: "https://www.mlbtraderumors.com/feed" },
  { feedTitle: "CBS Sports NFL", feedUrl: "https://www.cbssports.com/rss/headlines/nfl/" },
  { feedTitle: "Pro Football Rumors", feedUrl: "https://www.profootballrumors.com/feed" },
  { feedTitle: "NPR News", feedUrl: "https://feeds.npr.org/1001/rss.xml" },
  { feedTitle: "ABC News", feedUrl: "https://abcnews.go.com/abcnews/topstories" },
  { feedTitle: "CBS News", feedUrl: "https://www.cbsnews.com/latest/rss/main" },
  { feedTitle: "Stereogum", feedUrl: "https://www.stereogum.com/feed/" },
  { feedTitle: "The Quietus", feedUrl: "https://thequietus.com/feed?format=atom" },
];
